FROM osrf/ros2:devel

RUN apt update && apt upgrade -y
RUN apt install curl -y
RUN apt install git nano software-properties-common -y
RUN apt install gcc -y
RUN apt install python3 -y
RUN apt update && apt install ros-dev-tools -y
RUN apt install ros-iron-ros-base -y
RUN apt install ros-iron-plansys2-* -y

